apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}-client
  labels:
    app: {{.Chart.Name}}
data:
  {{.Chart.Name}}-client-cert: {{.Values.clientCert}}
  {{.Chart.Name}}-client-key: {{.Values.clientKey}}
  {{.Chart.Name}}-server-ca-cert: {{.Values.serverCaCert}}