apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
spec:
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
        project: {{.Values.project}}
    spec:
      containers:
      # App
      - name: {{.Chart.Name}}
        image: {{.Values.imageRepository}}/{{.Chart.Name}}:{{.Values.version}}
        volumeMounts:
        - name: {{.Chart.Name}}-server-secrets
          mountPath: /etc/secrets/{{.Chart.Name}}-server
          readOnly: true
        - name: jwt-verification-secret
          mountPath: /etc/secrets/jwt-verification
          readOnly: true
        ports:
        - name: grpc
          containerPort: 8443
        env:
        - name: SSL_SERVER_CERTIFICATE
          value: /etc/secrets/{{.Chart.Name}}-server/{{.Chart.Name}}-server-cert
        - name: SSL_SERVER_PRIVATE_KEY
          value: /etc/secrets/{{.Chart.Name}}-server/{{.Chart.Name}}-server-key
        - name: SSL_CLIENT_CA_CERTIFICATE
          value: /etc/secrets/{{.Chart.Name}}-server/{{.Chart.Name}}-client-ca-cert
        - name: JWT_SIGNATURE_VERIFICATION_KEY
          value: /etc/secrets/jwt-verification/jwt-verification-key
      # Gateway
      - name: {{.Chart.Name}}-gateway
        image: {{.Values.imageRepository}}/{{.Chart.Name}}-gateway:{{.Values.version}}
        volumeMounts:
        - name: {{.Chart.Name}}-client-secrets
          mountPath: /etc/secrets/{{.Chart.Name}}-client
          readOnly: true
        ports:
        - name: json
          containerPort: 9443
        env:
        - name: GATEWAY_PORT
          value: "9443"
        - name: CORS_ALLOWED_ORIGINS
          value: {{.Values.corsAllowedOrigins | quote}}
        - name: BACKEND_HOST
          value: {{.Chart.Name}}
        - name: BACKEND_PORT
          value: $({{.Chart.Name | upper}}_SERVICE_PORT_GRPC)
        - name: SSL_CA_CERTIFICATE
          value: /etc/secrets/{{.Chart.Name}}-client/{{.Chart.Name}}-ca-cert
        - name: SSL_CLIENT_CERTIFICATE
          value: /etc/secrets/{{.Chart.Name}}-client/{{.Chart.Name}}-client-cert
        - name: SSL_CLIENT_PRIVATE_KEY
          value: /etc/secrets/{{.Chart.Name}}-client/{{.Chart.Name}}-client-key
      volumes:
      - name: {{.Chart.Name}}-server-secrets
        secret:
          secretName: echod-server
      - name: {{.Chart.Name}}-client-secrets
        secret:
          secretName: {{.Chart.Name}}-client
      - name: jwt-verification-secret
        secret:
          secretName: {{.Values.jwtVerificationSecret}}