apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echod
    spec:
      containers:
      - name: echod
        image: vyshane/echod:1.0.0-SNAPSHOT
        ports:
        - name: grpc
          containerPort: 8443
      - name: echo-gateway
        image: vyshane/echo-gateway:1.0.0-SNAPSHOT
        ports:
        - name: json
          containerPort: 9443