apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}-server
  labels:
    app: {{.Chart.Name}}
data:
  {{.Chart.Name}}-server-cert: {{.Values.serverCert}}
  {{.Chart.Name}}-server-key: {{.Values.serverKey}}
  {{.Chart.Name}}-client-ca-cert: {{.Values.clientCaCert}}