apiVersion: v1
kind: Service
metadata:
  name: echod
  labels:
    app: echod
spec:
  ports:
  - name: grpc
    port: 8443
    targetPort: grpc
  # - name: rest
  #   port: 9443
  #   targetPort: rest
  selector:
    app: echod