name: echod
version: 1.0.0-SNAPSHOT
description: A starter kit for building microservices using gRPC and Scala
keywords:
  - Scala
  - gRPC
home: https://github.com/vyshane/grpc-scala-microservice-kit
sources:
  - https://github.com/vyshane/grpc-scala-microservice-kit
maintainers:
  - name: Vy-Shane Xie
    email: shane@node.mu
