# Default values for echod.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
project: grpc-scala-microservices-kit
imageRepository: vyshane 
app: echod
version: 1.0.0-SNAPSHOT
replicas: 1 
jwtVerificationSecret: jwt-verification
corsAllowedOrigins: "*, http://localhost:3000, https://node.mu"  # Development environment example
